spring:
  application:
    name: dynamic-form

  datasource:
    username: ${PSQL_USER:postgres}
    password: ${PSQL_PASS:postgres}
    url: jdbc:postgresql://${DB_HOST:postgresserver}:5432/${DB_NAME:dynamic_form_db}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    open-in-view: false

server:
  port: 8080

seed:
  database: ${SEED_DATABASE:false}

swagger:
  dev-url: http://localhost:8080
  prod-url: https://localhost:8080

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    default-models-expand-depth: 1
    default-model-expand-depth: 2
    display-request-duration: true
    doc-expansion: none
    persistAuthorization: true

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:36000000000}
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:36000000000}
